---
- name: Set SELinux to permissive
  vars:
    ansible_python_interpreter: /usr/bin/python2.6
  selinux:
    policy: targeted
    state: permissive

- name: install boto and botocore
  pip:
    name: ['boto', 'boto3', 'botocore']
    executable: /usr/local/bin/pip

- name: Create groups
  group:
    name: "chlservices"
    gid: "600"
    state: present

- name: Create users
  user:
    name: '{{ item.name }}'
    groups: '{{ item.groups }}'
    state: present
  with_items: '{{ users }}'

- name: Download Oracle setup files from s3
  aws_s3:
    bucket: development-eu-west-2.resources.ch.gov.uk
    object: '{{ s3_files_oracle }}'
    dest: "/tmp/{{ s3_files_oracle_name }}"
    mode: get
  
- name: Download application file 1 from s3
  aws_s3:
    bucket: development-eu-west-2.resources.ch.gov.uk
    object: '{{ s3_file_app_1 }}'
    dest: "/tmp/{{ s3_files_app_name1 }}"
    mode: get

- name: Download application file 2 from s3
  aws_s3:
    bucket: development-eu-west-2.resources.ch.gov.uk
    object: '{{ s3_file_app_2 }}'
    dest: "/tmp/{{ s3_files_app_name2 }}"
    mode: get

- name: List contents of /tmp
  command: ls -l /tmp
  register: tmpfiles
  ignore_errors: true
- name: Output of /tmp
  ansible.builtin.debug:
    msg: "{{ tmpfiles }}"
  ignore_errors: true

- name: Unarchive tar files
  unarchive:
    remote_src: yes
    src: "/tmp/{{ item }}"
    dest: "/tmp/{{ item | splitext | first }}"
  with_items: '{{ tar_files }}'

- name: List contents of /tmp - 2
  command: ls -l /tmp
  register: tmpfiles2
  ignore_errors: true
- name: Output of /tmp - 2
  ansible.builtin.debug:
    msg: "{{ tmpfiles2 }}"
  ignore_errors: true

- name: Install Oracle packages
  vars:
    ansible_python_interpreter: /usr/bin/python2.6
  yum:
     name: /tmp/oracle-instantclient11.2-basic-11.2.0.2.0.x86_64.rpm
     state: present

#- name: Install Oracle packages
  #vars:
    #ansible_python_interpreter: /usr/bin/python2.6
  #yum:
  #dnf:
     #name: /tmp/'{{ item }}'
     #state: present
  #with_items:
    #- oracle-instantclient11.2-basic-11.2.0.2.0.x86_64.rpm
    #- oracle-instantclient11.2-devel-11.2.0.2.0.x86_64.rpm
    #- oracle-instantclient11.2-sqlplus-11.2.0.2.0.x86_64.rpm

- name: Ensure env variables are set
  lineinfile:
    path: "{{ user_home_path }}/.bash_profile"
    line: '{{ item }}'
  with_items:
   - export LD_LIBRARY_PATH=/usr/lib/oracle/11.2/client64/lib/
   - export TNS_ADMIN=/usr/lib/oracle/11.2/client64/lib/

- name: Add config to ld.so.conf
  lineinfile:
    path: /etc/ld.so.conf
    line: '{{ item }}'
  with_items:
    - /usr/lib/oracle/11.2/client64/lib/
    - /usr/local/lib

- name: Run ldconfig
  command: /sbin/ldconfig

- name: Remove any exisitng Perl binaries
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - /usr/local/lib64/perl5 
    - /usr/local/share/perl5 
    - /usr/lib64/perl5/vendor_perl 
    - /usr/share/perl5/vendor_perl 
    - /usr/lib64/perl5 
    - /usr/share/perl5

- name: Install Perl binaries
  copy:
    src: /tmp/usr
    dest: /usr

- name: Install base application files to home path
  copy:
    src: "/tmp/{{ item }}"
    dest: '{{ user_home_path }}'
  with_items: '{{ user_home_path_content }}'

- name: Remove base application installation files
  file:
    path: "/tmp/{{ item }}"
    state: absent
  with_items: '{{ user_home_path_content }}'

- name: Delete installation files
  find:
    paths: /tmp
    patterns: 'oracle-instantclient*,*.tar.gz,*perl5,*vendor_perl,python*'
  register: files_to_delete

- name: Remove installation files
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ files_to_delete.files }}"
