---
- name: Set SELinux to permissive
  vars:
    ansible_python_interpreter: /usr/bin/python2.6
  selinux:
    policy: targeted
    state: permissive

- name: install boto and botocore
  pip:
    name: ['boto', 'boto3', 'botocore']
    executable: /usr/local/bin/pip

- name: Create groups
  group:
    name: "chlservices"
    gid: "600"
    state: present

- name: Create users
  user:
    name: '{{ item.name }}'
    groups: '{{ item.groups }}'
    state: present
  with_items: '{{ users }}'

# Can only download one object at a time
- name: Download Oracle setup files from s3 - basic rpm
  aws_s3:
    bucket: development-eu-west-2.resources.ch.gov.uk
    object: '{{ s3_files_oracle_basic_rpm }}'
    dest: "/tmp/{{ s3_files_oracle_basic_rpm_name }}"
    mode: get

- name: Download Oracle setup files from s3 - devel rpm
  aws_s3:
    bucket: development-eu-west-2.resources.ch.gov.uk
    object: '{{ s3_files_oracle_devel_rpm }}'
    dest: "/tmp/{{ s3_files_oracle_devel_rpm_name }}"
    mode: get

- name: Download Oracle setup files from s3 - sqlplus rpm
  aws_s3:
    bucket: development-eu-west-2.resources.ch.gov.uk
    object: '{{ s3_files_oracle_sqlplus_rpm }}'
    dest: "/tmp/{{ s3_files_oracle_sqlplus_rpm_name }}"
    mode: get

- name: Download static application files from s3
  aws_s3:
    bucket: development-eu-west-2.resources.ch.gov.uk
    object: '{{ s3_file_app_static }}'
    dest: "/tmp/{{ s3_files_app_static_name }}"
    mode: get

- name: Download application files from s3
  aws_s3:
    bucket: development-eu-west-2.resources.ch.gov.uk
    object: '{{ s3_file_app }}'
    dest: "/tmp/{{ s3_files_app_name }}"
    mode: get

- name: List contents of /tmp
  command: ls -l /tmp
  register: tmpfiles
  ignore_errors: true
- name: Output of /tmp
  ansible.builtin.debug:
    msg: "{{ tmpfiles }}"
  ignore_errors: true

- name: Unarchive tar files
  unarchive:
    remote_src: yes
    src: "/tmp/{{ item }}"
    dest: /tmp/
  with_items: '{{ tar_files }}'

- name: List contents of /tmp - 2
  command: ls -al /tmp
  register: tmpfiles2
  ignore_errors: true
- name: Output of /tmp - 2
  ansible.builtin.debug:
    msg: "{{ tmpfiles2 }}"
  ignore_errors: true

- name: Find contents of /tmp - 2
  command: find /tmp -name *.rpm
  register: tmpfiles3
  ignore_errors: true
- name: Output of find /tmp - 2
  ansible.builtin.debug:
    msg: "{{ tmpfiles3 }}"
  ignore_errors: true

- name: Find module mod_cookietrack
  command: find /tmp -name mod_cookietrack.so
  register: tmpfiles4
  ignore_errors: true
- name: Output of find module mod_cookietrack
  ansible.builtin.debug:
    msg: "{{ tmpfiles4 }}"
  ignore_errors: true

#- name: Install Oracle packages
  #vars:
    #ansible_python_interpreter: /usr/bin/python2.6
  #yum:
     #name: /tmp/oracle-database-10.2.0/oracle-instantclient11.2-basic-11.2.0.2.0.x86_64.rpm
     #state: present

#- name: Install Oracle packages
  #vars:
    #ansible_python_interpreter: /usr/bin/python2.6
  #yum:
     #name: "/tmp/{{ oracle_packages }}"
     #state: present

# Using 3 separate tasks as using a list caused failures in concourse pipeline
- name: Install Oracle packages - basic
  vars:
    ansible_python_interpreter: /usr/bin/python2.6
  yum:
     name: "/tmp/{{ oracle_packages_basic }}"
     state: present

- name: Install Oracle packages - devel
  vars:
    ansible_python_interpreter: /usr/bin/python2.6
  yum:
     name: "/tmp/{{ oracle_packages_devel }}"
     state: present

- name: Install Oracle packages - sqlplus
  vars:
    ansible_python_interpreter: /usr/bin/python2.6
  yum:
     name: "/tmp/{{ oracle_packages_sqlplus }}"
     state: present

- name: Ensure env variables are set
  vars:
    ansible_python_interpreter: /usr/bin/python2.6
  lineinfile:
    path: "{{ user_home_path }}/.bash_profile"
    line: '{{ item }}'
  with_items: '{{ env_var }}'
   #- export LD_LIBRARY_PATH=/usr/lib/oracle/11.2/client64/lib/
   #- export TNS_ADMIN=/usr/lib/oracle/11.2/client64/lib/

- name: Find contents of home env
  command: cat /home/ewf/.bash_profile
  register: homeenv
  ignore_errors: true
- name: Output of home env
  ansible.builtin.debug:
    msg: "{{ homeenv }}"
  ignore_errors: true

- name: Add config to ld.so.conf
  vars:
    ansible_python_interpreter: /usr/bin/python2.6
  lineinfile:
    path: /etc/ld.so.conf
    line: '{{ item }}'
  with_items: '{{ ld_so_conf }}'
    #- /usr/lib/oracle/11.2/client64/lib/
    #- /usr/local/lib

- name: Find contents of ld so conf
  command: cat /etc/ld.so.conf
  register: ldconf
  ignore_errors: true
- name: Output of ld so conf
  ansible.builtin.debug:
    msg: "{{ ldconf }}"
  ignore_errors: true

- name: Run ldconfig
  command: /sbin/ldconfig

- name: Remove any exisitng Perl binaries
  file:
    path: '{{ item }}'
    state: absent
  with_items: '{{ perl_binaries }}'
    #- /usr/local/lib64/perl5 
    #- /usr/local/share/perl5 
    #- /usr/lib64/perl5/vendor_perl 
    #- /usr/share/perl5/vendor_perl 
    #- /usr/lib64/perl5 
    #- /usr/share/perl5

- name: Find contents of perl binaries after delete
  command: ls -l /usr/lib64/perl5/vendor_perl
  register: perl_bin_before
  ignore_errors: true
- name: Output of perl binaries after delete
  ansible.builtin.debug:
    msg: "{{ perl_bin_before }}"
  ignore_errors: true

- name: Install Perl binaries
  copy:
    src: /tmp/usr
    dest: /
    remote_src: yes

- name: Find contents of perl binaries
  command: ls -l /usr/lib64/perl5/vendor_perl
  register: perl_bin
  ignore_errors: true
- name: Output of perl binaries
  ansible.builtin.debug:
    msg: "{{ perl_bin }}"
  ignore_errors: true

- name: Install base application files to home path
  copy:
    src: "/tmp/{{ item }}"
    dest: '{{ user_home_path }}'
    remote_src: yes
  with_items: '{{ user_home_path_content }}'

- name: Find app contents of home dir
  command: ls -l /home/ewf
  register: home_app
  ignore_errors: true
- name: Output of app home dir
  ansible.builtin.debug:
    msg: "{{ home_app }}"
  ignore_errors: true

- name: Remove base application installation files
  file:
    path: "/tmp/{{ item }}"
    state: absent
  with_items: '{{ user_home_path_content }}'

- name: Delete installation files
  find:
    paths: /tmp
    #patterns: 'oracle-instantclient*,*.tar.gz,usr,'
    patterns: '{{ files_to_remove }}'  
  register: files_to_delete

- name: Remove installation files
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ files_to_delete.files }}"

- name: Find /tmp final output
  command: ls -l /tmp
  register: tmp_final
  ignore_errors: true
- name: Output of /tmp final
  ansible.builtin.debug:
    msg: "{{ tmp_final }}"
  ignore_errors: true

- name: Remove any exisitng httpd.conf
  file:
    path: '{{ item }}'
    state: absent
  with_items: '{{ http_conf }}'
    #- /etc/httpd/conf/httpd.conf

- name: Find http conf before
  command: ls -l /etc/httpd/conf/httpd.conf
  register: http_conf1
  ignore_errors: true
- name: Output of http conf
  ansible.builtin.debug:
    msg: "{{ http_conf1 }}"
  ignore_errors: true

- name: Install httpd configs
  copy:
    src: "{{ item }}"
    dest: "/etc/{{ item }}"
    #owner: ewf
    owner: '{{ user }}'
    #group: chlservices
    group: '{{ group }}'
    mode: 0775
  with_items: '{{ http_config }}'
    #- httpd/conf.d/ewf_perl.conf
    #- httpd/conf/ewf_startup.pl
    #- httpd/conf/httpd.conf

- name: Find http conf 2
  command: ls -l /etc/httpd/conf/
  register: http_conf2
  ignore_errors: true
- name: Output of http conf
  ansible.builtin.debug:
    msg: "{{ http_conf2 }}"
  ignore_errors: true

- name: Start and enable httpd
  service:
    name: httpd
    state: started
    enabled: true