---
- name: Update System Packages
  yum:
    name: '*'
    state: latest
- name: Install dependencies
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{ base_ami_dependencies }}'
- name: Start and enable httpd
  service:
    name: httpd
    state: started
    enabled: True
