---
users:
  - name: ewf
    group: chlservices
    gid: 600
    
user_home_path: /home/ewf

s3_file_perl_lib: /application/ewf/frontend/ewf-frontend-static.tar.gz
s3_file_perl_lib_name: '{{ s3_file_app_static | basename }}'

tar_files:
  - "{{ s3_file_perl_lib_name }}"
