---  
- name: AMI Build
  hosts: ewf-frontend
  become: true
  gather_facts: yes
  vars:
    ansible_python_interpreter: /usr/local/bin/python3.6
  roles:
    - role: heritage-frontend-base
    - role: ewf-app-config
