---
- name: Apply mod_cookietrack.so http module
  copy:
    src: /tmp/etc/httpd/modules/mod_cookietrack.so
    dest: /etc/httpd/modules/mod_cookietrack.so
    mode: 0755
    remote_src: yes
 
- name: Delete installation files
  find:
    paths: /tmp
    patterns: 'etc'
  register: files_to_delete

- name: Remove installation files
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ files_to_delete.files }}"

- name: Start and enable httpd
  service:
    name: httpd
    state: started
    enabled: true
    
