---
- name: Download app library archive from s3
  aws_s3:
    bucket: '{{ s3_bucket }}'
    object: '{{ s3_file_perl_lib }}'
    dest: "/tmp/{{ s3_file_perl_lib_name }}"
    mode: get

- name: Unarchive app library download
  unarchive:
    remote_src: yes
    src: "/tmp/{{ s3_file_perl_lib_name }}"
    dest: /tmp/

- name: Apply mod_cookietrack.so http module
  vars:
    ansible_python_interpreter: /usr/bin/python2.6
  copy:
    src: /tmp/etc/httpd/modules/mod_cookietrack.so
    dest: /etc/httpd/modules/mod_cookietrack.so
    mode: 0755
    remote_src: yes
 
- name: Remove mod_cookietrack.so installation file
  file:
    path: /tmp/etc
    state: absent

- name: Install libapreq2 package for httpd mod_apreq2.so module requirement
  vars:
    ansible_python_interpreter: /usr/bin/python2.6
  yum:
     name: libapreq2
     state: present

- name: Copy config templates to relevant locations
  vars:
    ansible_python_interpreter: /usr/bin/python2.6
  copy:
    src: "{{ item }}"
    dest: "/{{ item }}"
    mode: 0755
  loop:
    - etc/httpd/conf/httpd.j2
    - etc/httpd/conf/ewf_startup.j2
    - etc/httpd/conf.d/ewf_perl.j2

- name: Copy deployment playbook onto server for build time
  vars:
    ansible_python_interpreter: /usr/bin/python2.6  
  copy:
    src: deployment.yml
    dest: /root/deployment.yml
    mode: 0755