---
- name: Apply mod_cookietrack.so http module
  vars:
    ansible_python_interpreter: /usr/bin/python2.6
  copy:
    src: /tmp/etc/httpd/modules/mod_cookietrack.so
    dest: /etc/httpd/modules/mod_cookietrack.so
    mode: 0755
    remote_src: yes
 
- name: Remove mod_cookietrack.so installation file
  file:
    path: /tmp/etc
    state: absent

#- name: Start and enable httpd
  #service:
    #name: httpd
    #state: started
    #enabled: true
    
